defmodule AnonymousNameGenerator.Adjective do
  @moduledoc false
  @adjectives {
    "abandoned", "acidic", "acrobatic", "adorable", "affectionate", "aged",
    "aggressive", "agile", "alert", "ambitious", "ancient", "angry", "anxious",
    "aromatic", "artistic", "attractive", "autumn", "aware",
    "bald", "beautiful", "beloved", "bewildered", "big", "billowing",
    "biodegradable", "bitter", "black", "blissful", "blue", "blushing",
    "bold", "boring", "bossy", "brave", "breezy", "broken", "bruised", "bubbly",
    "bumpy", "busy", "buzzing", "calm", "careful", "cautious", "charming",
    "cheery", "chilly", "chubby", "clean", "clever", "clumsy", "cold",
    "colossal", "cool", "creamy", "crimson", "cuddly", "damaged", "damp", "dark",
    "dawn", "dazzling", "decaying", "decent", "delayed", "delicate", "delicious",
    "delightful", "delirious", "devoted", "diligent", "dirty", "disgusting",
    "divine", "drab", "dry", "eager", "easy", "ecstatic", "edible", "elastic",
    "elderly", "elegant", "embarrassed", "empty", "expensive", "faithful", "fake",
    "falling", "famous", "fancy", "fast", "fat", "feisty", "fierce", "firm",
    "fit", "flabby", "flaky", "flashy", "flawed", "floral", "fluffy", "fragrant",
    "fresh", "frosty", "gaseous", "gentle", "giant", "gifted", "gigantic",
    "glamorous", "glaring", "glossy", "gorgeous", "greasy", "great", "greedy",
    "green", "grumpy", "hairy", "handsome", "happy", "haunting", "helpful",
    "helpless", "hidden", "holy", "hot", "huge", "icky", "icy",
    "immense", "important", "infinite", "interesting", "itchy", "jaded",
    "jealous", "jolly", "juicy", "jumpy", "kind", "lanky", "large", "late",
    "lazy", "lean", "legal", "lingering", "little", "lively", "long", "loose",
    "mad", "magnificent", "massive", "melted", "merry", "messy", "microscopic",
    "mighty", "miniature", "minty", "misty", "moist", "moldy", "morning",
    "muddy", "muscular", "mushy", "mysterious", "nameless", "nasty", "nervous",
    "nice", "nifty", "noxious", "numb", "nutritious", "nutty", "obedient",
    "obnoxious", "odd", "oily", "old", "optimistic", "patient", "pesky",
    "petite", "phony", "pitiful", "plain", "plump", "polished", "polite",
    "poor", "powerful", "prickly", "proud", "pungent", "purple", "pushy",
    "quaint", "quiet", "radiant", "rapid", "reckless", "red",
    "reflecting", "regal", "remorseful", "repulsive", "restless", "rich",
    "rigid", "ripe", "rough", "rowdy", "royal", "rude", "salty",
    "sarcastic", "savory", "scary", "scrawny", "scruffy", "secret", "shady",
    "shaggy", "sharp", "shiny", "short", "shrill", "shy", "silky",
    "silly", "sizzling", "skinny", "slimy", "slushy", "small", "snappy", "snowy",
    "solitary", "soupy", "sour", "sparkling", "spicy", "spring", "stale",
    "sticky", "still", "stocky", "strange", "strong", "summer", "sweaty",
    "sweet", "tall", "tame", "tangy", "tart", "tasty", "teeny", "tender",
    "terrible", "thankful", "throbbing", "tight", "tiny", "twilight",
    "uptight", "vast", "victorious", "wandering", "warm", "weak", "weathered",
    "wet", "white", "wild", "winter", "wispy", "withered", "witty", "wonderful",
    "worried", "young", "yummy", "zealous"
  }
  def adjectives, do: @adjectives
end
